server:
  port: 80
  servlet:
    context-path: /api

spring:
  autoconfigure:
    exclude:
  application:
    name: demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      pool-name: HikariPool-demo
      maximum-pool-size: 20
      minimum-idle: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
  redis:
    host: ${REDIS_HOST}
    port: 6399
    database: 0
    password: ${REDIS_PASSWORD}

#mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

#应用程序变量
application:
  env: ${APP_ENV}
  jwt:
    key: ${APP_JWT_KEY}
    refreshKey: ${APP_JWT_REFRESHKEY}


