server:
  port: 80
  servlet:
    context-path: /demo
  tomcat:
    threads:
      min-spare: 20
      max: 200
    connection-timeout: 20000

spring:
  application:
    name: demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_HOST}/${DB_DATABASE}?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT+8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: ${REDIS_DATABASE}
    password: ${REDIS_PASSWORD}

#mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml

